# This file was generated by GoReleaser. DO NOT EDIT.
cask "prosa-panel" do
  version "0.19.1"

  on_macos do
    on_intel do
      sha256 "3e94b1b54029f8545386468bbf52719aaac789ab1a51a0d04d3ec3b353b0ab01"
      url "https://github.com/c3-oss/prosa/releases/download/v#{version}/prosa-panel_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "97a16a44fbff639c42e1406f1660011501d4762a90671ffbbac2fd8bcdee0f50"
      url "https://github.com/c3-oss/prosa/releases/download/v#{version}/prosa-panel_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "c7d2088523b54a29f8bfc2564c1cf48f623e5337bfcfc7454dbabf8893c8203d"
      url "https://github.com/c3-oss/prosa/releases/download/v#{version}/prosa-panel_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "49d8a69c99cd8d04e69256b42ad66f9ab7be39981d64be62e8d15687bb437847"
      url "https://github.com/c3-oss/prosa/releases/download/v#{version}/prosa-panel_#{version}_linux_arm64.tar.gz"
    end
  end

  name "prosa-panel"
  desc "Unified history of AI agent sessions across devices"
  homepage "https://github.com/c3-oss/prosa"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "prosa-panel"

  # No zap stanza required

end
