# This file was generated by GoReleaser. DO NOT EDIT.
cask "prosa-panel" do
  version "0.23.1"

  on_macos do
    on_intel do
      sha256 "8bd996a46063192b68b96b88dc10b50174b7d90b83121bdc31377ec506a3aaee"
      url "https://github.com/c3-oss/prosa/releases/download/v#{version}/prosa-panel_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "3893140cbb83cb14a7902365635d302ee5ad5038f4a435117d9973afeb99ac1a"
      url "https://github.com/c3-oss/prosa/releases/download/v#{version}/prosa-panel_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "8d4c36371123fb9b6d2bdb2f948c56e9d5787cb3ed14cf580d8b871dfa7863c8"
      url "https://github.com/c3-oss/prosa/releases/download/v#{version}/prosa-panel_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "aa0ea8214331e10c8658cbd165eba380fdf55713e71e49c921cdfd8bc1ae3b3a"
      url "https://github.com/c3-oss/prosa/releases/download/v#{version}/prosa-panel_#{version}_linux_arm64.tar.gz"
    end
  end

  name "prosa-panel"
  desc "Unified history of AI agent sessions across devices"
  homepage "https://github.com/c3-oss/prosa"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "prosa-panel"

  # No zap stanza required

end
