# This file was generated by GoReleaser. DO NOT EDIT.
cask "prosa-panel" do
  version "0.29.2"

  on_macos do
    on_arm do
      sha256 "65fcc997528f52aec1edde4a1480fe42d5386c099d988dd3d6d944076f39a712"
      url "https://github.com/c3-oss/prosa/releases/download/v#{version}/prosa-panel_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "13d6c887d47f3502a906ea84fbee35275e2d951a6469e97b5eb488f2d50f0c1f"
      url "https://github.com/c3-oss/prosa/releases/download/v#{version}/prosa-panel_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "1527dcab47414e05eaf80eed3a388e27d57a732e8308ebe0587ee22d1878d959"
      url "https://github.com/c3-oss/prosa/releases/download/v#{version}/prosa-panel_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "3a9be42806036ff51d90e633e56c10ad2f04165f01362fcc9ba8929badf385f0"
      url "https://github.com/c3-oss/prosa/releases/download/v#{version}/prosa-panel_#{version}_linux_amd64.tar.gz"
    end
  end

  name "prosa-panel"
  desc "Unified history of AI agent sessions across devices"
  homepage "https://github.com/c3-oss/prosa"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "prosa-panel"

  # No zap stanza required
end
