# This file was generated by GoReleaser. DO NOT EDIT.
cask "prosa-server" do
  version "0.22.0"

  on_macos do
    on_intel do
      sha256 "3ea7dd305c886690414d5d3a84d5b0a3a309bc4834a6e6a72618b85436625092"
      url "https://github.com/c3-oss/prosa/releases/download/v#{version}/prosa-server_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "9051b38d41703d0a424f531bd8c9d420f05b22e0cc9e6b680fac0c895fda044d"
      url "https://github.com/c3-oss/prosa/releases/download/v#{version}/prosa-server_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "464d39e10672da89050009ffd7808e2391975f3b827c998f286557104105fe58"
      url "https://github.com/c3-oss/prosa/releases/download/v#{version}/prosa-server_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "91edd71dc7f318a0632b575f5edb2962f88a8c02cf8f464eea255347b2c28d27"
      url "https://github.com/c3-oss/prosa/releases/download/v#{version}/prosa-server_#{version}_linux_arm64.tar.gz"
    end
  end

  name "prosa-server"
  desc "prosa-server (API server)"
  homepage "https://github.com/c3-oss/prosa"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "prosa-server"

  # No zap stanza required

end
