# This file was generated by GoReleaser. DO NOT EDIT.
cask "prosa" do
  version "0.29.2"

  on_macos do
    on_arm do
      sha256 "c1a67a23f8dd7b6fdb1a968915164597309c351b2f44f3d4833ec7d2799bbbbd"
      url "https://github.com/c3-oss/prosa/releases/download/v#{version}/prosa_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "90ab67c449877818149ac3be9c573a4d57e7b1f3ec02e1a1268c65e0b21c2e43"
      url "https://github.com/c3-oss/prosa/releases/download/v#{version}/prosa_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "410a96ceeb06830373bc42936995f314418388209e843982ac5d7ecb4942907a"
      url "https://github.com/c3-oss/prosa/releases/download/v#{version}/prosa_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "a850262ba772477d30c7a80f193ecc79a2e83225723f8991fd776628df39ad3c"
      url "https://github.com/c3-oss/prosa/releases/download/v#{version}/prosa_#{version}_linux_amd64.tar.gz"
    end
  end

  name "prosa"
  desc "CLI for prosa"
  homepage "https://github.com/c3-oss/prosa"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "prosa"

  # No zap stanza required

  caveats <<~EOS
    To finish setup, run:

      prosa setup

    That walks through device auth, installs the LaunchAgent
    that keeps history in sync, and imports the first batch of
    AI-agent sessions.
  EOS
end
