# This file was generated by GoReleaser. DO NOT EDIT.
cask "prosa-server" do
  version "0.21.2"

  on_macos do
    on_intel do
      sha256 "d5e8e55f10bc89eaf8dd1c876f3737f591e0c274e81a4e731984475f53268e4b"
      url "https://github.com/c3-oss/prosa/releases/download/v#{version}/prosa-server_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "92e94702abbf4d39bd8b8c41394a10c331c1329868d4db7155a1178b82b345a3"
      url "https://github.com/c3-oss/prosa/releases/download/v#{version}/prosa-server_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "558c46103eb4610d7b9b86644acbb0945b65ddff0db4f8dc2197a6a129183886"
      url "https://github.com/c3-oss/prosa/releases/download/v#{version}/prosa-server_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "4b8a8fd1a6792a88c8008e8f22d58d65a7caf38e553afd90f1d4910f93211bde"
      url "https://github.com/c3-oss/prosa/releases/download/v#{version}/prosa-server_#{version}_linux_arm64.tar.gz"
    end
  end

  name "prosa-server"
  desc "prosa-server (API server)"
  homepage "https://github.com/c3-oss/prosa"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "prosa-server"

  # No zap stanza required

end
