# This file was generated by GoReleaser. DO NOT EDIT.
cask "prosa" do
  version "0.15.0"

  on_macos do
    on_intel do
      sha256 "fb898a91cbac616c17d1a41ae0432ee0420cdcb99e5961025658945a11bb2b61"
      url "https://github.com/c3-oss/prosa/releases/download/v#{version}/prosa_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "9bac77b486001d7b75d917f1b8453ef760d87515ba5fdb4404c478e2c5d3a3d8"
      url "https://github.com/c3-oss/prosa/releases/download/v#{version}/prosa_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "c02da18db0fb22aa21307da36d1335ae2482a1e73e6497e8c4d64a9ed65bb1b6"
      url "https://github.com/c3-oss/prosa/releases/download/v#{version}/prosa_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "0b73af788c1753f3416d460ca3d3a30e069b347d6197a6e812c77bdb6cf0afae"
      url "https://github.com/c3-oss/prosa/releases/download/v#{version}/prosa_#{version}_linux_arm64.tar.gz"
    end
  end

  name "prosa"
  desc "Unified history of AI agent sessions across devices"
  homepage "https://github.com/c3-oss/prosa"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "prosa"
  binary "prosa-server"
  binary "prosa-panel"

  # No zap stanza required

  caveats <<~EOS
    To finish setup, run:

      prosa setup

    That walks through device auth, installs the LaunchAgent
    that keeps history in sync, and imports the first batch of
    AI-agent sessions.
  EOS
end
