# This file was generated by GoReleaser. DO NOT EDIT.
cask "prosa" do
  version "0.24.0"

  on_macos do
    on_intel do
      sha256 "daa2b6e65be94c9cd351a22794fcd365879c47ea667c932f514691dde84ae6d3"
      url "https://github.com/c3-oss/prosa/releases/download/v#{version}/prosa_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "f1e678b843e2337d9202d3ba9b9de9044f4f05620f54ce76bf6b07403646a95c"
      url "https://github.com/c3-oss/prosa/releases/download/v#{version}/prosa_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "e8fbcbef680bf75b8108c9a7e220a40b5246dde5f43fe0d813a8e1fed032a0e0"
      url "https://github.com/c3-oss/prosa/releases/download/v#{version}/prosa_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "145c7541710438304026e5d4184a32a440ad8984d74a986e60ea4ac7997b4a7c"
      url "https://github.com/c3-oss/prosa/releases/download/v#{version}/prosa_#{version}_linux_arm64.tar.gz"
    end
  end

  name "prosa"
  desc "CLI for prosa"
  homepage "https://github.com/c3-oss/prosa"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "prosa"

  # No zap stanza required

  caveats <<~EOS
    To finish setup, run:

      prosa setup

    That walks through device auth, installs the LaunchAgent
    that keeps history in sync, and imports the first batch of
    AI-agent sessions.
  EOS
end
