# This file was generated by GoReleaser. DO NOT EDIT.
cask "prosa-server" do
  version "0.15.1"

  on_macos do
    on_intel do
      sha256 "8f2186be4fb63bc0257f34354b1dfba36bd2817487092bf51ef572bddda2a83f"
      url "https://github.com/c3-oss/prosa/releases/download/v#{version}/prosa-server_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "bc0d7fb33e94318f74703d2f5a3b4dfe166b002b939172a46ce5f22ce6e47cbe"
      url "https://github.com/c3-oss/prosa/releases/download/v#{version}/prosa-server_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "3f4749c52aa9afafc8b6a609cc9b1005c28d1966c9bf3cbfd6766ad5418d0260"
      url "https://github.com/c3-oss/prosa/releases/download/v#{version}/prosa-server_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "0c3c0856b31aabf3ab849f50c6b4c2d668aaff35c36d0899b07fdb79a6dafdd5"
      url "https://github.com/c3-oss/prosa/releases/download/v#{version}/prosa-server_#{version}_linux_arm64.tar.gz"
    end
  end

  name "prosa-server"
  desc "prosa-server (API server)"
  homepage "https://github.com/c3-oss/prosa"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "prosa-server"

  # No zap stanza required

end
